name: FullStack Challenge

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 'main'

jobs:
  NodeJS-CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: codebase/rdicidr-0.1.0
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '15.x'

      - run: npm install

      - run: npm run lint

      - run: npm run prettier

      - run: npm run test
        env:
          CI: true

      - run: npm run build
